package de.mehtrick.jnario2jvior;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import de.mehtrick.jnario2jvior.Jnario2Jvior;

public class JnarioToJviorTest {
	/**
	 * Basic Test. It will turn the feature file under src/test/resources into jviro.yml file.
	 * The file will be placed under "build/gen/java";
	 */
	@Test
	public void testSomeLibraryMethod() {
		Jnario2Jvior classUnderTest = new Jnario2Jvior();
		classUnderTest.convertToJvior("src/", "build/gen/java");
	}
}
